## TITLE
Andrew Xie, FA32, andrewxie.dev


### Abstract
In this paper, I will describe a proposed open-source project for a centralized administrative web app for a RSO that I participate in. After three years of being involved on the national staff for this RSO, I believe an administrative web app is important to standardize documents and records nationwide to reduce the time needed to clean the data submitted by the branches at various schools. In the past, significant effort was required to obtain and maintain the data due to a lack of established or enforced standards, and a web app would be valuable to attempt to rectify those issues.
### Introduction
The National Society of Pershing Rifles is a nationwide military-oriented honor society with dozens of chapters nationwide and run by a national staff of around a dozen undergraduate volunteers. The purpose of this paper is not to go into depth about the history or purpose the organization, so I will focus more on the structural issues that this notional app is intended to solve. 
Every semester, the national staff requires a few basic administrative tasks to be completed. This includes the paying of dues and the submission of unit strength reports. Additional tasks are not routinely conducted by the staff but are done on demand, such as password reset and funding requests from the various chapters to the national society. Currently, significant amounts of effort are spent attempting to sort through inconsistently formatted spreadsheets and manually processing that information to determine who needs to be pressured to pay dues. Additionally, tasks such as paying dues and signing up for the national convention are difficult to do due to the reliance on improperly integrated legacy systems. In the past two years while I was on staff, almost the entire efforts of the entire staff are spent on those few administrative tasks, either pestering local units to submit their documentation or sorting through poorly formatted reports into one master report for documentation purposes. 
By creating an app to automate the standardization of these processes, effort from the staff that is expended on cleaning data will be able to be used elsewhere, potentially helping the entire society innovate instead of stagnating every year when the school year starts and efforts are redirected towards accomplishing routine bureaucratic tasks. Additionally, this would help make the data usable for visualization and mapping, which is useful for the end of year debriefing given to the society at the end of a staff’s tenure at the National Convention.
While this may not be the most exciting app, I do intend to tackle these problems this year, so while I may not create a web app due to the limited time for debugging and polishing that I have, many of the concepts described in this paper will likely be implemented in an altered form. I’m personally still working on learning front-end development skills, so can’t speak to how this notional app should specifically be implemented.
### Purpose
An open-source project to address the above problems would be useful in this case due to being able to tap into the society’s membership at large, being transparent, and being resilient to frequent turnovers.  Additionally, an administrative app could be flexibly forked by other organizations with similar problems. This app would allow individuals to pay dues, submit unit strength reports, and to easily submit requests for funds and password resets to the national staff for evaluation. However, the bulk of the features will be in the back end, to ease the amount of manual processing needed to keep all the paperwork in line. 
Additional features and such can be added and expanded as needed depending on the evolving administrative load placed on the Pershing Rifles national staff. Ideally, this app will be flexible and modular enough to be able to handle expansion in scope with relative ease, if possible in a manner that requires minimal technical skills to actually expand the app.
### Target Audience and Community
As this project is being made for an existing society, the targeted audience would be the members of that society. This is a relatively narrow scope, even though membership is very diverse, from military academies to private schools. This audience would expand if the project is forked and used by another organization, however the priority of this app would be to serve the needs of Pershing Rifles and as such, seeking such an expanded audience is not something that will be intentionally done. 
Additionally, I’m not sure how much technical expertise there is among the society for the creation and maintenance of an app, so the app will remain under the oversight of the G-6 (IT) officer. It would be interesting to see if incentives to companies to contribute would work, though determining an appropriate reward and mechanism to give out awards would not be a priority. This initial development period would take some effort and recruitment for volunteers to develop and test the app would be done through the existing members of the society via mailing list announcement. 
Standards of behavior for contributors will continue to be extended through the standards taught through the military training programs that the vast majority of the society belong to, whether that be a military academy or ROTC. Integrity and professionalism will be expected and enforced via the existing society chain of command when possible, and contributors from outside the society will be on a 3-strike rule, waivable if the national staff determines that violations of standards are too egregious.
### Codebase Management
The code for this app would be stored on GitHub, potentially as a part of a GitHub organization. This would allow for maximum collaboration with the society at large and allow any other organizations who wish to fork this app to do so. I personally would prefer it to be under the MIT license, since if it is forked for other organizations, they may want to have their forks be closed source for security and privacy reasons. No data will be stored by the app, instead all information collected will be directed either through the dues infrastructure or packaged via email and sent to the relevant staff member after it is checked for standardization.
For our copy of the code, since the primary functions are backend functions for the staff and that this intended to be a web app that is reloaded every time a user visits the webpage it is hosted on, as long as the front end is not impacted new versions can be released and pushed to the live site on a rolling basis.  This live copy will not automatically update with new additions to the GitHub code for stability reasons, and any new versions will need to be approved by the G-6 (IT) officer before implementation. With that safeguard in place, I don’t believe that it is necessary to restrict contribution to the program, as there have been previous complaints that the national staff is not transparent enough to the society at large. Transparency in this app would help to bring some of that trust back. Within the National Society of Pershing Rifles, there may not be many people willing to work on an app as there is rarely enthusiasm for work beyond the local level, so keeping this project as open as possible and removing barriers to contribution will also be critical in maintaining as much interest and progress as possible.
Documentation will be kept in markdown files on the GitHub and using the wiki feature, and backup copies of the documentation will be kept in the society’s private servers as a backup. Documentation will consist of user instructions, explanations of the code and thought process of the design, and a brief text to assist with familiarization with the codebase. 
Within GitHub, as much standardization will be done as possible. There will be a set of standard labels made, and those labels will correspond to categories on the Trello described below. There will be standard descriptions for issues and requirements for thorough documentation via comments in issues.
I personally dislike the sprawl that comes with trying to use too many tools to manage a project, so the amount of unnecessary tracking tools and linkages will be reduced. Complexity leads to friction and steepens the learning curve, so limiting the project to GitHub and Trello until there is solid momentum built will be important. If the project expands to a degree that brings in ‘wicked’ problems, then this will be reexamined. Most likely, if such problems arise, then most of this paper will be invalid due to most of the discussion revolving around the assumption that this project will be conducted by a small team under the jurisdiction of an existing staff with an existing chain of command.
Progress and Feedback
Feedback from users will be tracked through issues on Github and through emails directly to the G-6 (IT) officer. At every monthly society-wide meeting, a request for feedback will be added to the G-6 (IT) officer’s slides, inviting company commanders to submit any feedback they have. Feedback for the back end will come from the G-1 (Administrative) and G-8 (Finance) officers primarily, as the former processes USRs and the latter dues payments. Feedback will have the option of being written directly as issues, and the G-6 (IT) officer will write up issues for any feedback that they receive via their avenues of communication.
Progress and assigned tasks among interested contributors will be done via Trello. While the app is in development, progress will be shared with the community during the aforementioned monthly meetings, and weekly to the Chief of Staff in order to keep upper leadership of the society informed. After the minimum viable product is created and deployed, further progress will be continuously tracked via the Trello, both to ensure that there is transparency regarding the development process and to ensure that there is a record of progress if needed.
An Agile Scrum approach to managing this project would be interesting. With the Trello board, planning a discrete set of tasks to be done in a certain amount of time would be easier. As the society consists of mostly undergraduate students with significant existing commitments, it could be more productive to plan features over the school year, then do one or more sprints over the summer. Summer sprints would be useful to make progress when students have the most free time, along with still being in the initial stages of the staff’s tenure after turnover in March, leading to more motivation for progress being present than during the school year. During the school year, efforts tend to be focused on maintaining the status quo and keeping everything running while motivation is steadily worn away as opposed to implementing new ideas and features enthusiastically, so sprints during the summer are logical. 
### Community
If there is enough interest and enthusiasm for development that a group of contributors forms, then more structure will be adopted. A positive side effect of this limited project could be the creation of a community within Pershing Rifles of people interested in software development.  This would be highly beneficial for the society, as with the wide geographic distribution, most functions rely heavily on software and internet capable tools, a team that has a strong understanding of those tools and the knowledge to create more tools would be invaluable as a force multiplier. There are two possible results that I will examine, a centralized community and a decentralized community.
This centralized community/team will be primarily lead by the G-6 (IT) officer and fall under the jurisdiction of that department. If the levels of enthusiasm for service with the national staff is any indication, the scale of this team is unlikely to reach more than a dozen members. The centralization of this team would allow it to be run in a relatively conventional manner, with frequent meetings for communication and projects being assigned by the G-6 (IT) officer to individual members. 
With the open-source aspect of this though, a decentralized aspect of community would inevitably evolve as the project gained more steam and started to be adopted in organizations outside of the national staff of the Pershing Rifles. There are a variety of ways that this could occur, from companies within Pershing Rifles adopting variations of the application locally or creating their own apps that plug into the national network, or if organizations outside of Pershing Rifles adopt the app for their own usage.
If the users are limited to Pershing Rifles members and units, then an extension of the centrally run bureaucracy would be possible. A further meeting of local representatives from each team could meet monthly with the centralized G-6 (IT) team, as an extension of the society wide monthly meetings. At these meetings, discussions about functionalities implemented at the local level that should be incorporated at the national level and requests for interfaces to plug local software into could be made and investigated, with easier tasks being done in the intervening month and more difficult tasks being reserved for sprints in the summer as previously described.
In the event that external teams start to get involved, if there is still a manageably small number of teams involved, then meetings as described above would proceed in a similar fashion. In the improbably event that such a project picks up enough momentum to become a large-scale project on the international level, then further reexamination of plans would be required and this militaristic style of organization would become infeasible. However, an expansion at this level would be beneficial in increasing the available possibilities due to reducing the restraints of a small team with limited time.
Hypothetical Expansion
With a larger team, expansion of the scope of this project would be possible. It would be interesting to increase the flexibility of the core system and its modularity, though this would likely be too basic of a concept to be taken far without radical reorganization. A description of a potential expansion in scope would probably fall outside the scope of this paper, since this paper is examining methods of project management and not the actual granular details of how this project should be, so I will refrain from wasting space with that discussion.
### Sustainability
In order to avoid the fate of all other IT related projects in Pershing Rifles, significant thought must be devoted to sustainability. As this is intended to be a web app, such sustainability would be difficult, if not impossible, to achieve even in the short term without active maintenance. However, an attempt to expand the possible unmaintained lifespan of the app can be done by relying as little on dependencies as possible and by making this app as much of a closed system as possible. After the core of this project is created, then further expansion by whatever community can be done by said community. 
It may be worthwhile to create a more permanent app, capable of being run locally and in a language such as C that has endured and will likely endure. The local app would have to be able to clean data from the lack of standardization, as opposed to restricting input data in a fashion that creates data. I am unfamiliar with techniques that would enable this, however this is where an expanded community could be useful. The expanded expertise associated with an expanded community would be helpful in this case, allowing for a better expansion of the project. As I cannot predict how this would expand, the best structure for this expansion would have to be decided after the character and tendencies of this expanded community is determined.
### Conclusion
I admit that I likely did not pick a particularly good project for a 10 page paper on management techniques, however this is a project I’m actively looking at starting and so it was on my mind. A lot of the management methods and styles that I would use in a notional project will have to depend on the type of community that develops and the scale of that community. 
I’ve been a part of multi-year projects, where each year the developers change, and in that community, continuity was maintained solely through GitHub. This model required a lot of effort for every new team, as there was no turnover, and more than half the time of each new team’s tenure was spent trying to make sense of older code. Despite this, complex machines and controller code were completed rapidly. I visit the organization every winter when I’m home, and the progress is amazing. The project I inherited was nothing more than an obsolete motion tracker hooked up to a motor, with no GUI and requiring extensive terminal use to run, and 2 years later it was rewired and assembled inside of a protective case, with a fully functional GUI, capable of autonomous running and ready to be installed as an exhibit. 
I’ve also been a project manager in a team that never got out of the planning phase, so had plenty of documentation and snippets of prototype code with nothing to show for it. This latter team had a GitLab, wikis, massive banks of Q&As and recorded knowledge, but was stymied by overambition and the desire to have a perfect first attempt. Everyone wanted to be on the technical team and neglected administration, yet no technical work was done due to the constantly changing goals and lack of strong leadership. I believe this RSO has since either dissolved or lost all of its talent to rival RSOs.
One project with minimal documentation and actual management that was completed rapidly, another with a lot of management and tools but with no progress. These experiences colored by view of project management before I took this class, and to a great extent still do. The tools and methods introduced in this class will be invaluable for my personal project management in the future, in the very slim chance I go into project management in software, so I did learn from this class. I do believe that projects generally differ to an extent where specific implementation of those tools and methods has to be considered on a case by case basis and applied in a flexible manner though, so there’s only so much that I can imagine for this notional project.
